const heroCardsArray = [
    "BETTER D!",
    "BUH, BYE!",
    "DOUBLE UP!",
    "GET THAT OUTTA HERE!",
    "GETTING PAID!",
    "HELPING HAND!",
    "NOT THIS TIME!",
    "ONE MORE TIME!",
    "SAMESIES!",
    "SIX-IT!",
    "SO WILD!",
    "TIP IT!",
    "TRANSFERENCE!",
    "TRIPLE UP!",
    "TRY, TRY AGAIN!",
    "TWICE AS WILD!",
    "VEGAS BABY!",
    "WHAT STATUS EFFECTS?",
    "ARCING SHIELD",
    "CONDUCTIVITY!",
    "EUREKA",
    "HIGH VOLTAGE!",
    "JOLT",
    "MAXIMUM POWER!",
    "NANITE ASSAULT!",
    "NUTS N' BOLTS",
    "OOOH SHINY!",
    "OVERCLOCK",
    "POWER UP",
    "RATCHET UP",
    "ROBO REVENGE!",
    "SCHEMATICS",
    "SCRAP COLLECTOR",
    "SCRATCH BUILT",
    "SPANNER STRIKE",
    "SWARMING BOTS",
    "SYNTHESIZE!",
    "ZAPPPP!",
    "ADRENALINE SURGE!",
    "CONCUSS!",
    "CRIT BASH",
    "CRIT SMASH",
    "FEELIN' GOOD!",
    "FORTITUDE",
    "GET SOME!",
    "HEAD BASH!",
    "MIGHTY BLOW",
    "OVERPOWER",
    "RAGE!",
    "RECKLESS",
    "SMACK",
    "STURDY BLOW",
    "THICK SKIN",
    "WAR CRY",
    "ABYSSAL WALK",
    "AHOY MATEY",
    "AVAST YE",
    "BATTEN DOWN!",
    "BLACK SOUL",
    "BLACK SPOT",
    "CROW'S NEST!",
    "CURSED",
    "CURSED CARDS!",
    "CURSED TOUCH!",
    "CUTLASS STRIKE",
    "DREAD MARK",
    "FEED THE FISH!",
    "HEAVE-HO!",
    "HIGH STAKES!",
    "LIGHT IT UP!",
    "LIGHT THE FUSE",
    "PILLAGE!",
    "PIRATE'S LIFE!",
    "PIRATE'S TOUCH!",
    "RANSOM!",
    "RUN YA THROUGH!",
    "SCURVY!",
    "SHARK BAIT!",
    "SHIVER ME TIMBERS",
    "SOUL CUTLASS",
    "SWASHBUCKLE!",
    "THAR SHE BLOWS",
    "THE SHIVERING",
    "TRUCE!",
    "WALK THE PLANK",
    "X MARKS THE SPOT",
    "YO HO!",
    "BOUNTY HUNTER",
    "DEADEYE",
    "DUEL",
    "EAT LEAD!",
    "ENFORCER",
    "FAN THE HAMMER",
    "FILL'EM WITH LEAD!",
    "MARK THE TARGET",
    "PISTOL WHIP",
    "QUICK DRAW",
    "REVOLVER",
    "ROULETTE!",
    "RUN AND GUN!",
    "SHOWDOWN",
    "SPIN THE CHAMBER!",
    "TAKE COVER",
    "WANTED!",
    "WILD WEST!",
    "ANIMALISTIC",
    "BLOOD BOND!",
    "FERAL",
    "FERAL INSTINCTS",
    "FEROCIOUS",
    "HUNT",
    "JUGULAR",
    "JUNGLE FURY!",
    "MATERNAL BOND",
    "ONSLAUGHT",
    "POUNCE!",
    "PREDATORY ADVANCE",
    "PRIMAL ROAR!",
    "PROWL!",
    "RESILIENT!",
    "RESUSCITATE",
    "SAVAGE",
    "SAVAGE SLASH!",
    "SWIPE",
    "COMBO STRIKE",
    "CONTEMPLATE!",
    "ENLIGHTENMENT!",
    "FIST OF HARMONY",
    "FIST OF TRANQUILITY",
    "FIST STRIKE",
    "LOTUS STRIKE",
    "MEDITATE",
    "MYSTIC MANTRA!",
    "PALM STRIKE!",
    "RUMINATE!",
    "SERENITY",
    "TEMPEST RUSH",
    "TRANSCENDENCE!",
    "WAY OF THE LOTUS",
    "WAY OF THE MONK",
    "ZEN STRIKE",
    "BLINDING SHOT",
    "COVERED SHOT",
    "DEMISING SHOT",
    "ECLIPSE",
    "ENTANGLING SHOT",
    "EVADE!",
    "EVASIVE ACTION",
    "EXPLODING ARROW",
    "FOCUS",
    "LONGBOW",
    "LUNAR BLESSING",
    "LUNAR ECLIPSE!",
    "LUNAR UMBRA!",
    "MISSED ME",
    "MOON MAGIC!",
    "MOON SHADOW",
    "TAKE THAT!",
    "VOLLEY!",
    "ASSASSINATE!",
    "DEATH BLOSSOM",
    "DOJO!",
    "ESCAPE!",
    "FAN OF KNIVES!",
    "JUGULATE",
    "KUJI-KIRI",
    "MISDIRECT",
    "POISON BLADE",
    "POISON DART!",
    "SHADE SHIFT",
    "SHADEWALK",
    "SHADOW FANG",
    "SLASH",
    "SMOKE OFFERING!",
    "SMOKE SCREEN",
    "THROWING STARS!",
    "TIP OF THE BLADE",
    "TRAIN!",
    "WALK THE LINE",
    "ABSOLUTION!",
    "BLESSED!",
    "CONSECRATION!",
    "DIVINE DEFENSE",
    "DIVINE FAVOR!",
    "HOLY ATTACK",
    "HOLY LIGHT",
    "MIGHTY PRAYER",
    "MIGHTY!",
    "OFFENSIVE STANCE",
    "PROSPERITY",
    "REQUITAL",
    "RESOLUTE FAITH!",
    "RETALIATE",
    "RIGHTEOUS COMBAT",
    "RIGHTEOUS PRAYER",
    "STEADFAST",
    "TITHE",
    "BLAZING SOUL",
    "BURNING SOUL",
    "COMBUSTION",
    "FIRE UP!",
    "FIREBALL",
    "HOT STREAK",
    "HUZZAH!",
    "IGNITE",
    "INFERNAL INFUSION!",
    "METEORITE",
    "METEOROID",
    "MOLTEN ARMOR",
    "PYROBLAST",
    "RED HOT!",
    "SCORCH",
    "SCORCH THE EARTH!",
    "WARM UP!",
    "BUDO",
    "BUSHIDO",
    "DON'T BACK DOWN!",
    "EMPOWER",
    "FOLLOW THROUGH!",
    "GISHI!",
    "HAGA",
    "HAGAKURE",
    "HONORABLE!",
    "KATANA SLICE",
    "KENSEI!",
    "MASAMUNE",
    "SHAME ON YOU!",
    "SHOGUN!",
    "SOLEMN",
    "SOLEMNITY",
    "STAND TALL",
    "WAKIZASHI",
    "ANGELIC COMBAT!",
    "ANGELIC MANTLE",
    "ARCHANGEL'S WILL",
    "CHERUBIM",
    "DIVINE INTERVENTION!",
    "DIVINE VISAGE",
    "GLORIOUS",
    "HEAVEN'S BLESSING",
    "HIGHEST POWER",
    "HOLIER THAN THOU!",
    "HOLY BLADE",
    "HOLY COMMAND",
    "HOLY SMITE",
    "PURIFY",
    "SMOTE!",
    "SPLIT THE HEAVENS!",
    "TAKE FLIGHT",
    "TO THE SKIES!",
    "TRIUMPHANT",
    "CARD TRICK!",
    "CARDUCOPIA",
    "COUNTER STRIKE",
    "DAGGER STRIKE",
    "ENTER THE SHADOWS!",
    "INSIDIOUS STRIKE",
    "PICKPOCKET",
    "POISON WOUND!",
    "SHADOW COIN!",
    "SHADOW DANCE",
    "SHADOW DEFENSE",
    "SHADOW MELD!",
    "SHADOW SHANK!",
    "SHADOW STRIKE",
    "SHANK ATTACK",
    "SHIFTY STRIKE",
    "SNEAKY!",
    "WILD SHADOW!",
    "AMBUSH!",
    "BUNKER UP!",
    "CARPET BOMB",
    "COUNTERMEASURES",
    "DISENGAGE!",
    "EXPLOIT",
    "FEIGNED RETREAT!",
    "FLANK",
    "HIGHER GROUND!",
    "INDIRECT APPROACH",
    "INTERDICTION",
    "MANEUVER",
    "PROFITEER",
    "RECONNAISSANCE",
    "SABER STRIKE",
    "STRATEGIC APPROACH",
    "STRATEGIZE",
    "UPPER HAND!",
    "WAR ROOM!",
    "BITTERROOT",
    "CALL OF THE WILD",
    "CULTIVATE",
    "CULTIVATE!",
    "DOWN POUR!",
    "DRINK DEEP!",
    "ENRAPTURE",
    "FERTILIZE",
    "HARVEST!",
    "MOTHER TREE!",
    "NATURE'S BLESSING",
    "NATURE'S GRASP",
    "OVERGROWTH",
    "PLANT",
    "ROOTED",
    "SPLINTER",
    "STOMP!",
    "TEND",
    "VENGEFUL VINES",
    "WAKE THE FOREST!",
    "WILL O' WISP!",
    "BLOOD BOIL!",
    "BLOOD FLOW!",
    "BLOOD LETTING!",
    "BLOOD MAGIC",
    "BLOOD THIRST",
    "BLOOD TIDE!",
    "CONSUME BLOOD!",
    "DARK OMEN!",
    "DRAW BLOOD",
    "EXSANGUINATE!",
    "GASH",
    "GLAMOUR",
    "GOUGE",
    "HEMORRHAGE",
    "IMMORTAL FLESH",
    "INFLUENCE",
    "LIMB FROM LIMB!",
    "POSSESS",
    "PRESENCE",
    "REND",
    "SANGUIMANCY"
    ]